language: node_js
node_js:
  - 10
services:
  - docker
addons:
  apt:
    packages:
      # Updating Docker.
      - docker-ce
jobs:
  include:
    - stage: "Tests"
      script: docker-compose -f docker-compose.yml -f dc-development.yml run --rm -e NODE_ENV=test backend bash -c 'npm test && npm run report-coverage'

    - stage: "Docker-Deployment"
      script: ./docker/helpers/dockerHubUpload.sh
