language: node_js
node_js:
  - 10
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - docker-compose -f docker-compose.yml -f dc-development.yml run --rm backend npm test
after_success:
  - docker-compose -f docker-compose.yml -f dc-production.yml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag hb-image-prod sandunwebdev/hb-backend-image-prod:master
  - docker push sandunwebdev/hb-backend-image-prod:master
