language: node_js
node_js:
  - 10
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - echo docker --version
  - npm run docker:build:prod
script:
  - npm run docker:test:dev
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag hb-image-prod sandunwebdev/hb-backend-image-prod:master
  - docker push sandunwebdev/hb-backend-image-prod:master
